### ISSUE TITLE
state_qd.hpp

### ISSUE THREAD

**Issue by bossdm** [adaptive-intelligent-robotics/AURORA#1]
Hi,

I cannot find the header state_qd.hpp  in the qd-branch of sferes2. The include

`#include <sferes/stat/state_qd.hpp>`

is made on several places in the code. Could you include that header to the project? Also, what is the difference with the usual state.hpp and how important is that?

Kind regards

**Comment by Lookatator** [comment]
Hi,

Indeed, it seems forgot to make our sferes2 fork public. 

Following your comment, we made it public, and you can find the up-to-date repository at the following location (with the tag `AURORA`): [https://github.com/Lookatator/sferes2/tree/AURORA](https://github.com/Lookatator/sferes2/tree/AURORA).
This corresponds to the version of sferes2 that we developed in the [AIRL lab](https://github.com/adaptive-intelligent-robotics) for our personal needs. 

We will soon make some pull requests on the official sferes2 repo.

The only difference with state.hpp, is that [state_qd.hpp](https://github.com/Lookatator/sferes2/blob/AURORA/sferes/stat/state_qd.hpp) serialises the parents and offspring from the QualityDiversity class. I don't think that is super important in the case of AURORA. However, it is necessary to have it for Novelty Search and TAXONS, as in their case, the parents and offspring are not selected from the container.

If you have any additional question, feel free to ask :)

Best regards

**Comment by bossdm** [comment]
Thanks a lot, I will use this branch of sferes2 instead.
